// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Movie struct {
	ID          pgtype.UUID
	Title       pgtype.Text
	Director    pgtype.Text
	ReleaseAt   pgtype.Date
	TicketPrice pgtype.Numeric
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type Person struct {
	ID        pgtype.UUID
	FirstName pgtype.Text
	LastName  pgtype.Text
}
