// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: movies.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAllMovies = `-- name: GetAllMovies :many
SELECT id, title, director, release_at, ticket_price, created_at, updated_at from movies
`

func (q *Queries) GetAllMovies(ctx context.Context) ([]Movie, error) {
	rows, err := q.db.Query(ctx, getAllMovies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Movie
	for rows.Next() {
		var i Movie
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Director,
			&i.ReleaseAt,
			&i.TicketPrice,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMovie = `-- name: GetMovie :one
SELECT id, title, director, release_at, ticket_price, created_at, updated_at from movies where id = $1
`

func (q *Queries) GetMovie(ctx context.Context, id pgtype.UUID) (Movie, error) {
	row := q.db.QueryRow(ctx, getMovie, id)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Director,
		&i.ReleaseAt,
		&i.TicketPrice,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
